-- Workshop Jobs page: header buttons + board toolbar + job-card labels (zh, th, ja, es, pt, fr).
-- Merges into existing language packs (nothing already translated is overwritten). Run in Supabase SQL Editor.

UPDATE app_translations SET t = (t::jsonb || '{"bookInCar":"接车登记","searchSpare":"搜索配件","sendBookingLink":"发送预约链接","inviteWorkshop":"邀请修车厂","sendBookingLinkHint":"向客户发送预约链接","inviteWorkshopHint":"邀请其他修车厂"}'::jsonb) WHERE lang = 'zh';
UPDATE app_translations SET t = (t::jsonb || '{"bookInCar":"รับรถเข้าอู่","searchSpare":"ค้นหาอะไหล่","sendBookingLink":"ส่งลิงก์จองคิว","inviteWorkshop":"เชิญอู่ซ่อมรถ","sendBookingLinkHint":"ส่งลิงก์จองคิวให้ลูกค้า","inviteWorkshopHint":"เชิญอู่ซ่อมรถอื่น"}'::jsonb) WHERE lang = 'th';
UPDATE app_translations SET t = (t::jsonb || '{"bookInCar":"入庫受付","searchSpare":"部品を検索","sendBookingLink":"予約リンクを送る","inviteWorkshop":"整備工場を招待","sendBookingLinkHint":"お客様に予約リンクを送る","inviteWorkshopHint":"他の整備工場を招待"}'::jsonb) WHERE lang = 'ja';
UPDATE app_translations SET t = (t::jsonb || '{"bookInCar":"Ingresar vehículo","searchSpare":"Buscar repuesto","sendBookingLink":"Enviar enlace de reserva","inviteWorkshop":"Invitar taller","sendBookingLinkHint":"Enviar enlace de reserva a un cliente","inviteWorkshopHint":"Invitar a otro taller"}'::jsonb) WHERE lang = 'es';
UPDATE app_translations SET t = (t::jsonb || '{"bookInCar":"Registar viatura","searchSpare":"Procurar peça","sendBookingLink":"Enviar link de marcação","inviteWorkshop":"Convidar oficina","sendBookingLinkHint":"Enviar link de marcação a um cliente","inviteWorkshopHint":"Convidar outra oficina"}'::jsonb) WHERE lang = 'pt';
UPDATE app_translations SET t = (t::jsonb || '{"bookInCar":"Enregistrer le véhicule","searchSpare":"Chercher une pièce","sendBookingLink":"Envoyer le lien de réservation","inviteWorkshop":"Inviter un atelier","sendBookingLinkHint":"Envoyer le lien de réservation à un client","inviteWorkshopHint":"Inviter un autre atelier"}'::jsonb) WHERE lang = 'fr';

-- ── Jobs board toolbar + job-card labels ─────────────────────────────────────
UPDATE app_translations SET t = (t::jsonb || '{"wsSearchBoard":"搜索工单…","wsRefreshJobs":"刷新工单","wsZoomOut":"缩小","wsZoomIn":"放大","wsPhotos":"照片","wsHidePhotosTip":"隐藏车辆照片","wsShowPhotosTip":"显示车辆照片","wsHideFinished":"隐藏已完成","wsFinishedHidden":"已隐藏完成项","wsShowFinishedTip":"显示「已收款」和「已取消」列","wsHideFinishedTip":"收起「已收款」和「已取消」列 — 专注进行中的工作","wsInspection":"检查","wsBooked":"已预约","wsNoDateSelected":"未选择日期","wsBtnInvoice":"开发票"}'::jsonb) WHERE lang = 'zh';
UPDATE app_translations SET t = (t::jsonb || '{"wsSearchBoard":"ค้นหาในบอร์ด…","wsRefreshJobs":"รีเฟรชงาน","wsZoomOut":"ย่อ","wsZoomIn":"ขยาย","wsPhotos":"รูปภาพ","wsHidePhotosTip":"ซ่อนรูปรถ","wsShowPhotosTip":"แสดงรูปรถ","wsHideFinished":"ซ่อนงานที่เสร็จ","wsFinishedHidden":"ซ่อนงานที่เสร็จแล้ว","wsShowFinishedTip":"แสดงคอลัมน์ รับชำระแล้ว และ ยกเลิก","wsHideFinishedTip":"ซ่อนคอลัมน์ รับชำระแล้ว และ ยกเลิก — โฟกัสงานที่กำลังทำ","wsInspection":"ตรวจสภาพ","wsBooked":"จองแล้ว","wsNoDateSelected":"ยังไม่ได้เลือกวันที่","wsBtnInvoice":"ใบแจ้งหนี้"}'::jsonb) WHERE lang = 'th';
UPDATE app_translations SET t = (t::jsonb || '{"wsSearchBoard":"ボードを検索…","wsRefreshJobs":"作業を更新","wsZoomOut":"縮小","wsZoomIn":"拡大","wsPhotos":"写真","wsHidePhotosTip":"車の写真を隠す","wsShowPhotosTip":"車の写真を表示","wsHideFinished":"完了を隠す","wsFinishedHidden":"完了を非表示中","wsShowFinishedTip":"「入金済み」と「キャンセル」の列を表示","wsHideFinishedTip":"「入金済み」と「キャンセル」の列を折りたたむ — 進行中の作業に集中","wsInspection":"点検","wsBooked":"予約済み","wsNoDateSelected":"日付未選択","wsBtnInvoice":"請求書"}'::jsonb) WHERE lang = 'ja';
UPDATE app_translations SET t = (t::jsonb || '{"wsSearchBoard":"Buscar en el tablero…","wsRefreshJobs":"Actualizar trabajos","wsZoomOut":"Alejar","wsZoomIn":"Acercar","wsPhotos":"Fotos","wsHidePhotosTip":"Ocultar fotos de coches","wsShowPhotosTip":"Mostrar fotos de coches","wsHideFinished":"Ocultar terminados","wsFinishedHidden":"Terminados ocultos","wsShowFinishedTip":"Mostrar las columnas Pago recibido y Cancelado","wsHideFinishedTip":"Contraer las columnas Pago recibido y Cancelado — centrarse en el trabajo activo","wsInspection":"Inspección","wsBooked":"Reservado","wsNoDateSelected":"Sin fecha seleccionada","wsBtnInvoice":"Factura"}'::jsonb) WHERE lang = 'es';
UPDATE app_translations SET t = (t::jsonb || '{"wsSearchBoard":"Pesquisar no quadro…","wsRefreshJobs":"Atualizar trabalhos","wsZoomOut":"Reduzir","wsZoomIn":"Ampliar","wsPhotos":"Fotos","wsHidePhotosTip":"Ocultar fotos das viaturas","wsShowPhotosTip":"Mostrar fotos das viaturas","wsHideFinished":"Ocultar concluídos","wsFinishedHidden":"Concluídos ocultos","wsShowFinishedTip":"Mostrar as colunas Pagamento recebido e Cancelado","wsHideFinishedTip":"Recolher as colunas Pagamento recebido e Cancelado — focar no trabalho ativo","wsInspection":"Inspeção","wsBooked":"Marcado","wsNoDateSelected":"Sem data selecionada","wsBtnInvoice":"Fatura"}'::jsonb) WHERE lang = 'pt';
UPDATE app_translations SET t = (t::jsonb || '{"wsSearchBoard":"Rechercher dans le tableau…","wsRefreshJobs":"Actualiser les interventions","wsZoomOut":"Dézoomer","wsZoomIn":"Zoomer","wsPhotos":"Photos","wsHidePhotosTip":"Masquer les photos de véhicules","wsShowPhotosTip":"Afficher les photos de véhicules","wsHideFinished":"Masquer terminés","wsFinishedHidden":"Terminés masqués","wsShowFinishedTip":"Afficher les colonnes Paiement reçu et Annulé","wsHideFinishedTip":"Réduire les colonnes Paiement reçu et Annulé — se concentrer sur le travail en cours","wsInspection":"Inspection","wsBooked":"Réservé","wsNoDateSelected":"Aucune date choisie","wsBtnInvoice":"Facture"}'::jsonb) WHERE lang = 'fr';
